config/routes.rb
Rails.application.routes.draw do
  resource :sessions, only: [:new, :create, :destroy] 
  get '/oturum_ac', to: 'sessions#new', as: :login
  delete '/oturum_kapat', to: 'sessions#destroy', as: :logout


  resources :users, except: :index
  get '/users/new', to: redirect('/kayit')
  get '/kayit', to: 'users#new', as: :register
  get '/:id', to: 'users#show', as: :profile
  get '/:id/edit', to: 'users#edit', as: :edit_profile  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :username,
		exclusion: { in: ['oturum_ac'] },
		presence: true,
		uniqueness: { case_sensitive: false },
		length: { in: 4..12 },
		format: { with: /\A[a-zA-Z][a-zA-Z0-9_-]*\Z/ }

	validates :first_name,
		presence: true

	validates :last_name,
		presence: true

	validates :email,
		presence: true,
		uniqueness: { case_sensitive: false },
		email: true

=begin	
		validates :password, 
		presence: true,
		length: { minimum: 6 }
=end

	def to_param
		username		
	end
	
	def name
		"#{first_name} #{last_name}"
	end

	def user_detail
		"#{first_name} #{last_name} -- #{username} -- #{email} -- #{password_digest}"
	end

	def avatar_url
		hash_value = Digest::MD5.hexdigest(email.downcase)
		'http://gravatar.com/avatar/#{hash_value}?s=160'
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :signed_in?, :current_user, :login
	private

	def login(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def signed_in?
		current_user		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_username(params[:session][:user_name])

  	if user && user.authenticate(params[:session][:password])
  		login(user)
  		redirect_to profile_path(user), notice: 'Oturum Acildi.'
  	else
  		flash.now[:error] = 'Kullanici adi veya parola hatali.'
  		render :new
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to login_path, notice: 'Oturumunuz sonlandirildi.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :select_user, only: [:show, :edit, :update, :destroy]
	before_action :allowed?, only: [:edit, :create, :destroy]

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save	
			login(@user)
			redirect_to profile_path(@user), notice: 'Aramiza hos geldin!'
		else
			render :new
		end
	end

	def show
		@data = []

		if params[:sayfa]
			render layout: 'profile', locals: {page: params[:sayfa]}
		else
			render layout: 'profile', locals: {page: 'konular'}
		end
	end

	def edit
		render layout: 'profile'
	end

	def update
		# Bir tur guvenlik acigi engellemesi, 
		# user_params'da :password var ise bunlari silerek update_params olusturuluyor.
		update_params = user_params # begin
		if update_params.has_key?(:password)
			update_params.delete([:password, :password_confirmation])
		end # end

		if @user.update(user_params)
			redirect_to profile_path(@user), notice: 'Profil bilgileriniz guncellendi.'
		else
			render :edit, layout: 'profile'
		end
	end

	def destroy
		@user.destroy
		redirect_to '/'		
	end

	private

	def user_params
		params.require(:user).permit!
	end

	def select_user
		@user = User.find_by_username(params[:id])
	end

	def allowed?
		user = select_user

		unless current_user == user
			redirect_to profile_path(user), alert: 'Bunu yapmaya yetkiniz yok'
		end	
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(type)
		{ notice: 'info', alert: 'warning', error: 'danger' }[type.to_sym]		
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
	<div class="alert alert-<%= flash_class(type) %> alert-dismissible fade show" role="alert">
		<%= message %>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
<% end -%>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark">
	<a class="navbar-brand" href="/">Rails on Forum</a>
	
	<div class="collapse navbar-collapse justify-content-end">
		<% if signed_in? %>
			<div class=" navbar-nav nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"><%= current_user.name %></a>
				<div class="dropdown-menu">
					<%= link_to 'Profilimi Goruntule', profile_path(current_user), class: 'dropdown-item' %>
					<%= link_to 'Oturumu Kapat', logout_path, method: :delete, class: 'dropdown-item' %>
				</div>
			</div>
		<% else %>
			<ul class="navbar-nav">
				<li class="nav-item">
					<%= link_to 'Kaydol', register_path, class: 'nav-link' %>
				</li>
				<li class="nav-item">
					<%= link_to 'Oturum Ac', login_path, class: 'nav-link' %>
				</li>
			</ul>
		<% end -%>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>RailsOnForm</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	
	<%= render 'layouts/nav_bar' %>

	<div class="container p-2">
		<%= render 'layouts/flash_messages' %>

		<%= content_for?(:content) ? yield(:content) : yield %>
	</div>

</body>
</html>

app/views/layouts/profile.html.erb
<%= content_for(:content) do %>
	<div class="row m-2 p-2">
		<div class="col-2">
			<%= image_tag @user.avatar_url, class: 'rounded-circle' %>
		</div>

		<div class="col-10">
			<h2><%= @user.name %></h2>
			<p><%= @user.email %></p>
			<div class="btn-group">
					<%= link_to 'Konular', profile_path(@user, sayfa: 'konular'), class: 'btn btn-dark' %>
					<%= link_to 'Yorumlar', profile_path(@user, sayfa: 'yorumlar'), class: 'btn btn-dark' %>
					<% if current_user == @user %>
						<%= link_to 'Profilimi Duzenle', edit_profile_path(@user), class: 'btn btn-dark' %>
						<%= link_to 'Hesabimi Sil', @user, class: 'btn btn-dark', data: {confirm: 'Hesabinizi silmek istediginize...?'}, method: :delete %>
					<% end -%>
			</div>
		</div><hr>
	</div>

	<div class="m-2 p-2">
		<%= yield :profile_content %>
	</div>
<% end -%>

<%= render template: 'layouts/application' %>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true, validate: true do |form| %>
	<% if @user.errors.any? %>
		<div class="card text-white bg-danger mb-3" style="max-width: 39rem;">
			<div class="card-header">
				<h3>Asagidaki hatalari duzeltip, tekrar deneyiniz.</h3>
			</div>
			<div class="card-body">
				<ul>
					<% @user.errors.full_messages.each do |message| %>
						<li class="text-light"><%= message %></li>
					<% end %>
				</ul>
			</div>
		</div>

	<% end -%>

	<div class="form-row">
		<div class="form-group col-md-6">
			<%= form.label :first_name,
				for: 'InputFirstName' %>
			<%= form.text_field :first_name, 
				class: 'form-control', 
				id: 'InputFirstName',
				type: 'text',
				placeholder: 'First Name' %>
		</div>

		<div class="form-group col-md-6">
			<%= form.label :last_name, 
				for: 'InputLastName' %>
			<%= form.text_field :last_name,
				class: 'form-control', 
				id: 'InputLastName',
				type: 'text',
				placeholder: 'Last Name' %>
		</div>
	</div>

	<div class="form-group">
		<%= form.label :username,
			for: 'InputUserName' %>
		<%= form.text_field :username,
			class: 'form-control', 
			id: 'InputUserName',
			type: 'text',
			placeholder: 'Username' %>
	</div>

	<div class="form-group">
		<%= form.label :email,
			for: 'InputEmail' %>
		<%= form.email_field :email,
			class: 'form-control', 
			id: 'InputEmail',
			type: 'email',
			placeholder: 'Email' %>
	</div>

	<% if params[:action] == 'new' || params[:action] == 'create' %>
		<div class="form-row">
			<div class="form-group col-md-6">
				<%= form.label :password,
					for: 'InputPassword' %>
				<%= form.password_field :password,
					class: 'form-control', 
					id: 'InputPassword',
					type: 'password',
					placeholder: 'Password' %>
			</div>

			<div class="form-group col-md-6">
				<%= form.label :password_confirmation,
					for: 'InputPasswordConf' %>
				<%= form.password_field :password_confirmation,
					class: 'form-control', 
					id: 'InputPasswordConf',
					type: 'password',
					placeholder: 'Password' %>
			</div>
		</div>
	<% end -%>

	<div class="d-flex justify-content-end">
		<%= form.submit 'Sign up',
			class: 'btn btn-primary',
			type: 'submit' %>
	</div>
<% end %>

app/views/users/edit.html.erb
<%= content_for(:profile_content) do %>
	<h2>Profilimi Duzenle</h2>
	<%= render 'form' %>
<% end -%>

app/views/users/new.html.erb
<div class="row m-2 p-2">

	<div class="col-md-7 m-2 p-2">
		<h2>Aramiza katilin!</h2>
		<%= render 'form' %>
	</div>


	<div class="col-md-5 card text-white bg-dark m-2 p-2" style="max-width: 25rem; max-height: 25rem;">
		<div class="card-header">
			<h3>Buralarda yeni misin?</h3>
		</div>
		<div class="card-body">
			<p>O halde; hemen bir hesap olustur ve bu buyu aileye katil!</p>
			<ul>
				<li>Takildigin sorularla ilgili sorular sor.</li>
				<li>Digerlerinin sorularini cevapla.</li>
				<li>Ilgi alanlarini takip et ve tartismalara dahil ol.</li>
			</ul>

			<p class="font-weight-bold">
				Ogrenirken, ogretmek icin yandaki formu doldurarak baslayabilirsin.
			</p>
		</div>
	</div>

</div>

app/views/users/show.html.erb
<% content_for(:profile_content) do %>
	<h2><%= page.capitalize %></h2>

	<% if @data.blank? %>
		<p>Kullaniciya ait <%= page %> bulunmamaktadir</p>
	<% else %>
		<% @data.each do |data| %>
			<div><%= data %></div>
		<% end -%>
	<% end -%>
<% end -%>